---
title: "Lab_6"
author: "Alejandro Alfaro"
date: "3/09/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message=F, warning=F )
library(maptools)
library(sp)
library( rgeos )
library(rgdal)
library(raster)
library( sp )
library(maps)
library( spatialEco )
library(bitops)
library( RCurl )
library(maptools)
```
```{r}
# Part 1:

## (1)	Download the Tiger shapefiles for Onondaga County census tracts and primary and secondary roads (see attached). Plot both together, highlighting interstates.
dir.create( "shapefiles" )
setwd( "./shapefiles" )
download.file("ftp://ftp2.census.gov/geo/tiger/TIGER2010/TRACT/2010/tl_2010_36067_tract10.zip", "onondaga census tracts.zip" )
unzip( "onondaga census tracts.zip" )
file.remove( "onondaga census tracts.zip" )
syr <- readShapePoly( fn="tl_2010_36067_tract10", proj4string=CRS("+proj=longlat +datum=WGS84") )
syr <- syr[ as.numeric(as.character(syr$NAME10)) < 64 , ] # keep only tracts in the city

### ADD ROADS
download.file("ftp://ftp2.census.gov/geo/tiger/TIGER2015/PRISECROADS/tl_2015_36_prisecroads.zip", "primary_and_secondary_roads.zip" )
unzip( "primary_and_secondary_roads.zip" )
file.remove( "primary_and_secondary_roads.zip" )
roads <- readShapeLines( fn="tl_2015_36_prisecroads", proj4string=CRS("+proj=longlat +datum=WGS84") )
roads <- roads[ roads$RTTYP == "I" , ] # keep only interstates

## Clipping roads

clipped_roads <- gIntersection( syr, roads )

## (4)	Create a buffer of approximately a quarter mile (eyeball this) from the interstate, and identify all houses that fall within this zone.

buff1 <- gBuffer( clipped_roads, width=.0025, byid=T )
par( mar=c(0,0,0,0) )
plot( syr,  border="gray80" )
plot( clipped_roads, col="steelblue", lwd=2, add=T )
plot(buff1, col=rgb( red=0.8, blue=0.4, green=0.7, alpha=0.5 ),lwd=.5, add=T)

## (5)	Add a new categorical variable to the houses dataset that indicates whether it falls within the buffer zone or not. 
dathouse <- read.csv("https://raw.githubusercontent.com/R-Class/all-labs-ddmii-aalfaroa/master/Lab5/HousingData_All.csv")
lon.lat <- dathouse[ , c("lon","lat") ]
lon.lat <- SpatialPoints(lon.lat, proj4string = CRS("+proj=longlat +datum=WGS84") )
poly.data.matched.to.points <- over( lon.lat, buff1 )
dathouse <- cbind( dathouse, poly.data.matched.to.points )
names(dathouse)[names(dathouse)=="poly.data.matched.to.points"] <- "Interstatebuff"
rm(poly.data.matched.to.points)

# Part 2:

## (1) Create a buffer a quarter mile from industrial zones (LandUse).  Create a plot to highlight your buffer zone.
link <- "https://raw.githubusercontent.com/lecy/geojson/master/syr_parcels.geojson"
syrland <- readOGR(dsn=link, layer="OGRGeoJSON")
syrindustrial <- syrland[syrland$LandUse == "Industrial",]
buff2 <- gBuffer( syrindustrial, width=.003)
par( mar=c(0,0,0,0) )
plot( syrland,  border=F, col = "grey80")
plot( syrindustrial, col="red", lwd=2, add=T)
plot(buff2, col=rgb( red=0.8, blue=0.4, green=0.7, alpha=0.5 ),lwd=.5, add=T)
## (2) Identify houses within the buffer zone and create a categorical variable in the dataset indicating proximity to industrial zones.
lon.lat <- dathouse[ , c("lon","lat") ]
lon.lat <- SpatialPoints(lon.lat, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0 ") )
buff2 <- spTransform(buff2, CRS(proj4string(lon.lat)))
poly.data.matched.to.points <- over( lon.lat, buff2 )
dathouse <- cbind( dathouse, poly.data.matched.to.points )
names(dathouse)[names(dathouse)=="poly.data.matched.to.points"] <- "Industrialbuff"
rm(poly.data.matched.to.points)

##(3)	Create a buffer zone an eighth of a mile from schools. Create a plot go highlight these buffer zones.
syrschools <- syrland[syrland$LandUse == "Schools",]
buff3 <- gBuffer(syrschools, width=.0015)
par( mar=c(0,0,0,0) )
plot( syrland,  border=F, col = "grey80")
plot( syrschools, col="red", lwd=2, add=T)
plot(buff3, col=rgb( red=0.8, blue=0.4, green=0.7, alpha=0.5 ),lwd=.5, add=T)

##(4)	Identify houses within the buffer zone and create a categorical variable in the dataset indicating proximity to schools.
buff3 <- spTransform(buff3, CRS(proj4string(lon.lat)))
poly.data.matched.to.points <- over( lon.lat, buff3 )
dathouse <- cbind( dathouse, poly.data.matched.to.points )
names(dathouse)[names(dathouse)=="poly.data.matched.to.points"] <- "Schoolbuff"
rm(poly.data.matched.to.points)
head(dathouse, 5)
```
