---
title: "Lab_5"
author: "Alejandro Alfaro"
date: "2/27/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( message=F, warning=F )
library( spatialEco )
library( sp )
library(bitops)
library( RCurl )
library(maptools)
library(devtools)
library(censusapi)
library(openxlsx)
library( ggmap )
library(dplyr)
library(pander)
```


# 1. Setting up housing dataset
```{r}
my.url <- "https://raw.githubusercontent.com/lecy/hedonic-prices/master/Data/Housing%20Price%20In-Class%20Exercise%20(Responses).csv"
housing.raw <- getURL( my.url, ssl.verifypeer=FALSE )
dathouse <- read.csv( textConnection(housing.raw), stringsAsFactors=FALSE )
names( dathouse ) <- c("timestamp","price","X1","X2","sqft","your.name","lot.size","beds",
                  "bath","garage","year","elementary","middle","high","walk","tax","highway",
                  "restaurant","starbucks","park","mall","address","zip","tract" )
rm(my.url)
rm(housing.raw)


dathouse$price <- as.numeric( gsub( ",","", dathouse$price ) )
dathouse$tax <- as.numeric( gsub( ",","", dathouse$tax ) )
dathouse$lot.size <- as.numeric( gsub( ",","", dathouse$lot.size ) )
dathouse$sqft <- as.numeric( gsub( ",","", dathouse$sqft ) )
dathouse$lot.size[ is.na( dathouse$lot.size ) ] <- mean( dathouse$lot.size, na.rm=T )

# houses <- dathouse[ , c("address","zip") ]
# houses$address <- gsub( ",", "", houses$address )
# houses$address <- gsub( "\\.", "", houses$address )
# addresses <- paste( houses$address, "Syracuse, NY", houses$zip, sep=", " )
# lat.long <- geocode( addresses )
# geocodehouses <- lat.long
# write.csv(geocodehouses, file="HousesGeocode.csv")
geocodehouses <- read.csv("HousesGeocode.csv")
dathouse$lon <- geocodehouses$lon
dathouse$lat <- geocodehouses$lat
rm(geocodehouses)
```


# 2. Add Census Tracts to each Home
```{r}
# #dir.create( "shapefiles" )
# setwd( "./shapefiles" )
# download.file("ftp://ftp2.census.gov/geo/tiger/TIGER2010/TRACT/2010/tl_2010_36067_tract10.zip", "onondaga census tracts.zip")
# unzip( "onondaga census tracts.zip" )
# file.remove( "onondaga census tracts.zip" )
setwd( "./shapefiles" )
onondaga <- readShapePoly( fn="tl_2010_36067_tract10", proj4string=CRS("+proj=longlat +datum=WGS84") )

#Spatial join 1
coordinates(dathouse) = ~lon+lat
proj4string(dathouse) <- '+proj=longlat +datum=WGS84'
poly.data.matched.to.points <- over( dathouse, onondaga )
dathouse@data <- cbind( dathouse@data, poly.data.matched.to.points )
pts.poly <- point.in.poly( dathouse, onondaga )
dathouse@data <- pts.poly@data
rm(poly.data.matched.to.points)
rm(pts.poly)
```

# 3. Add Census Data to Each Home
```{r}
library(plyr)
library(dplyr)
mycesuskey <- "6623ba8c58d3b2eeec361d16664573e96d878534"
datcensus <- getCensus(name = "acs5", vintage= "2015",
                 key = mycesuskey, vars= c("NAME","B17001_002E","B19013_001E", "B01001A_001E",
                                           "B01001B_001E", "B01001D_001E", "B01001I_001E"),
                 region="tract:*", regionin="State:36")
datcensus <- subset(datcensus, county == "067")
datcensus <- plyr::rename(datcensus, c("B17001_002E"="PovertyLevel", "B19013_001E"="MedHInc",
                                 "B01001A_001E"="White", "B01001B_001E"="Black",
                                 "B01001D_001E"="Asian", "B01001I_001E"="Latino"))
dathouse <- merge(x=dathouse, y=datcensus, by.x="TRACTCE10", by.y="tract",all.x=T)
rm(mycesuskey)
rm(datcensus)
```


# 4. Aggregrate by Census tract and add to the dataset
```{r}
# Add Crime data
crimedata <- read.xlsx("Crime in Syracuse Dec to Jan 2014.xlsx")
# addresses <- paste( crimedata$Address, crimedata$City, "NY", sep=", " )
# lat.long <- geocode( addresses )
# geocodecrime <- lat.long
# write.csv(geocodecrime, file="CrineGeocode.csv")
geocodecrime <- read.csv("CrimeGeocode.csv")
crimedata$lon <- geocodecrime$lon
crimedata$lat <- geocodecrime$lat
crimedatafiltered <- is.na(!crimedata$lat)
crimedata <- crimedata[!crimedatafiltered,]
rm(crimedatafiltered)
rm(geocodecrime)

#Spatial join 2
coordinates(crimedata) = ~lon+lat
proj4string(crimedata) <- '+proj=longlat +datum=WGS84'
poly.data.matched.to.points <- over( crimedata, onondaga)
crimedata@data <- cbind( crimedata@data, poly.data.matched.to.points )
pts.poly <- point.in.poly( crimedata, onondaga )
crimedata@data <- pts.poly@data
crimedatafinal <- data.frame(table(crimedata$TRACTCE10))
crimedatafinal <- plyr::rename(crimedatafinal, c("Var1"="Ctract", "Freq"="Crimes"))
dathouse <- merge(x=dathouse, y=crimedatafinal, by.x="TRACTCE10", by.y="Ctract", all.x=T)
rm(poly.data.matched.to.points)
rm(pts.poly)
rm(crimedatafinal)
rm(crimedata)
```


#Printing
```{r}
head(dathouse, 10)
```